kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: zeebe-regional
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: gp2
  fsType: ext4

